"""
Raw-text sources for the NOVA text corpus.

Every source yields Document(lang, source, text) and stops once it has
produced `max_bytes` of UTF-8 text. Only openly licensed material is used:

    Wikipedia (sk, cs, pl, en)   CC BY-SA 4.0   wikimedia/wikipedia on HF
    Python standard library      PSF License    local /usr/lib/python3.x
    Rust standard library        MIT / Apache-2.0   rust-src from static.rust-lang.org
"""

from __future__ import annotations

import hashlib
import io
import json
import re
import subprocess
import sysconfig
import tarfile
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

WIKI_DATASET = "wikimedia/wikipedia"
WIKI_SNAPSHOT = "20231101"

LICENSES = {
    "wikipedia": "CC BY-SA 4.0",
    "python-stdlib": "PSF License",
    "rust-src": "MIT OR Apache-2.0",
    "identity": "own (Creator)",
    "self-model": "own (generated from NOVA's own state)",
    "teacher": "generated by local teacher models (EXPERIMENTAL)",
    "web": "CC BY-SA 4.0 (web learner, EXPERIMENTAL)",
}

# Headings after which a Wikipedia article is only references/links.
WIKI_TAIL_HEADINGS = {
    "referencie", "reference", "references", "przypisy",
    "externé odkazy", "externí odkazy", "external links", "linki zewnętrzne",
    "pozri aj", "související články", "see also", "zobacz też",
    "literatúra", "literatura", "bibliografia", "further reading",
    "poznámky", "notes", "uwagi", "zdroje",
}


@dataclass
class Document:
    lang: str
    source: str
    text: str
    prompt: str = ""
    reasoning: str = ""

    @property
    def key(self) -> str:
        return hashlib.sha256(self.text.encode("utf-8")).hexdigest()


# ------------------------------------------------------------------ cleaning

_WS = re.compile(r"[ \t]+")
# NBSP, narrow NBSP, thin/figure spaces etc. -> plain space
_UNICODE_SPACES = re.compile(r"[\u00a0\u2000-\u200a\u202f\u205f\u3000]")


def normalize_spaces(text: str) -> str:
    return _UNICODE_SPACES.sub(" ", text)
_BLANKS = re.compile(r"\n{3,}")


def clean_wiki_text(text: str) -> str:
    text = normalize_spaces(text)
    lines = []
    for line in text.splitlines():
        if line.strip().lower().rstrip(":") in WIKI_TAIL_HEADINGS:
            break
        lines.append(_WS.sub(" ", line).rstrip())
    return _BLANKS.sub("\n\n", "\n".join(lines)).strip()


def clean_code(text: str) -> str:
    text = normalize_spaces(text).replace("\r\n", "\n").replace("\t", "    ")
    return _BLANKS.sub("\n\n", text).strip()


# ----------------------------------------------------------------- wikipedia

def _hf_json(url: str) -> object:
    with urllib.request.urlopen(url, timeout=60) as r:
        return json.load(r)


def wikipedia(
    lang: str,
    max_bytes: int,
    cache_dir: Path,
    min_chars: int = 500,
) -> Iterator[Document]:
    import pyarrow.parquet as pq
    from huggingface_hub import hf_hub_download

    config = f"{WIKI_SNAPSHOT}.{lang}"
    tree = _hf_json(
        f"https://huggingface.co/api/datasets/{WIKI_DATASET}/tree/main/{config}"
    )
    shards = sorted(x["path"] for x in tree if x["path"].endswith(".parquet"))
    if not shards:
        raise RuntimeError(f"No parquet shards for {config}")

    produced = 0
    for shard in shards:
        local = hf_hub_download(
            WIKI_DATASET,
            shard,
            repo_type="dataset",
            cache_dir=str(cache_dir),
        )
        pf = pq.ParquetFile(local)
        for batch in pf.iter_batches(columns=["text"], batch_size=512):
            for text in batch.column(0).to_pylist():
                text = clean_wiki_text(text or "")
                if len(text) < min_chars:
                    continue
                yield Document(lang, "wikipedia", text)
                produced += len(text.encode("utf-8"))
                if produced >= max_bytes:
                    return


# ------------------------------------------------------------ python stdlib

def python_stdlib(
    max_bytes: int,
    max_file_bytes: int = 200_000,
) -> Iterator[Document]:
    root = Path(sysconfig.get_paths()["stdlib"])
    produced = 0
    for path in sorted(root.rglob("*.py")):
        parts = set(path.parts)
        if "site-packages" in parts or "dist-packages" in parts:
            continue
        try:
            if path.stat().st_size > max_file_bytes:
                continue
            text = clean_code(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError):
            continue
        if len(text) < 200:
            continue
        yield Document("py", "python-stdlib", text)
        produced += len(text.encode("utf-8"))
        if produced >= max_bytes:
            return


# ---------------------------------------------------------------- rust-src

def _rustc_version() -> str:
    out = subprocess.run(
        ["rustc", "--version"], capture_output=True, text=True, check=True
    ).stdout
    return out.split()[1]


def rust_src(
    max_bytes: int,
    cache_dir: Path,
    max_file_bytes: int = 200_000,
) -> Iterator[Document]:
    version = _rustc_version()
    archive = cache_dir / f"rust-src-{version}.tar.xz"
    if not archive.exists():
        cache_dir.mkdir(parents=True, exist_ok=True)
        url = f"https://static.rust-lang.org/dist/rust-src-{version}.tar.xz"
        with urllib.request.urlopen(url, timeout=300) as r:
            archive.write_bytes(r.read())

    produced = 0
    with tarfile.open(archive, "r:xz") as tar:
        members = sorted(
            (m for m in tar.getmembers()
             if m.isfile() and m.name.endswith(".rs")
             and "/tests/" not in m.name and "/benches/" not in m.name
             and m.size <= max_file_bytes),
            key=lambda m: m.name,
        )
        for m in members:
            f = tar.extractfile(m)
            if f is None:
                continue
            try:
                text = clean_code(io.TextIOWrapper(f, encoding="utf-8").read())
            except UnicodeDecodeError:
                continue
            if len(text) < 200:
                continue
            yield Document("rs", "rust-src", text)
            produced += len(text.encode("utf-8"))
            if produced >= max_bytes:
                return


# ------------------------------------------------------------ teacher data

def teacher_jsonl(directory: Path, max_bytes: int) -> Iterator[Document]:
    """Accepted teacher answers (data/teacher_v*/<teacher>.jsonl)."""
    produced = 0
    for path in sorted(Path(directory).glob("*.jsonl")):
        for line in path.read_text(encoding="utf-8").splitlines():
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            answer = (rec.get("text") or "").strip()
            if not answer:
                continue
            yield Document(
                rec["lang"], "teacher", answer,
                prompt=rec.get("prompt", ""),
                reasoning=rec.get("reasoning", ""),
            )
            produced += len(answer.encode("utf-8"))
            if produced >= max_bytes:
                return


def web_jsonl(directory: Path, max_bytes: int) -> Iterator[Document]:
    """Texts collected by the web learner (data/web_v*/<lang>.jsonl)."""
    produced = 0
    for path in sorted(Path(directory).glob("*.jsonl")):
        for line in path.read_text(encoding="utf-8").splitlines():
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            text = (rec.get("text") or "").strip()
            if not text:
                continue
            yield Document(rec["lang"], "web", text)
            produced += len(text.encode("utf-8"))
            if produced >= max_bytes:
                return
